//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class partidas
    {
        public int idPartida { get; set; }
        public string idJugador { get; set; }
        public Nullable<System.DateTime> tiempoJugado { get; set; }
    
        public virtual tbJugadores tbJugadores { get; set; }
    }
}
